
services:
  r1:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net14:
        ipv4_address: 10.0.14.4 # to ha
      net16_0:
        ipv4_address: 10.0.16.2 # to r2
      net16_8:
        ipv4_address: 10.0.16.10 # to r4

  r2:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net16_0:
        ipv4_address: 10.0.16.3 # to r1
      net16_16:
        ipv4_address: 10.0.16.19 # to r3
  
  r3:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net15:
        ipv4_address: 10.0.15.4 # to hb
      net16_16:
        ipv4_address: 10.0.16.18 # to r2
      net16_24:
        ipv4_address: 10.0.16.26 # to r4

  r4:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net16_8:
        ipv4_address: 10.0.16.11 # to r1
      net16_24:
        ipv4_address: 10.0.16.27 # to r3

  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net14:
        ipv4_address: 10.0.14.3 # to r1

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net15:
        ipv4_address: 10.0.15.3 # to r3

networks:
  net14: # ha-r1
    ipam:
      driver: default
      config:
        - subnet: 10.0.14.0/24
  net15: # hb-r3
    ipam:
      driver: default
      config:
        - subnet: 10.0.15.0/24
  net16_0: # r1-r2
    ipam:
      driver: default
      config:
        - subnet: 10.0.16.0/29
  net16_8: # r1-r4
    ipam:
      driver: default
      config:
        - subnet: 10.0.16.8/29
  net16_16: # r3-r2
    ipam:
      driver: default
      config:
        - subnet: 10.0.16.16/29
  net16_24: # r3-r4
    ipam:
      driver: default
      config:
        - subnet: 10.0.16.24/29
